apiVersion: v1
kind: ConfigMap
metadata:
  name: obs-config
  namespace: obs-v0
data:
  KAFKA_BROKERS: "kafka-service:9092"
  ORDER_SERVICE_PORT: "3001"
  INVENTORY_SERVICE_PORT: "3002"
  PAYMENT_SERVICE_PORT: "3003"
  NOTIFICATION_SERVICE_PORT: "3004"
  NODE_ENV: "production"
