apiVersion: v1
kind: Secret
metadata:
  name: obs-secrets
  namespace: obs-v0
type: Opaque
data:
  # Supabase Postgres connection string (base64 encoded)
  DATABASE_URL: "cG9zdGdyZXNxbDovL3Bvc3RncmVzLmx6dHRqYm90a3ZidWlqZ3J5YXJlOmllTWRoQ2VsUlB3aE10QW5AYXdzLTEtYXAtc291dGhlYXN0LTIucG9vbGVyLnN1cGFiYXNlLmNvbTo1NDMyL3Bvc3RncmVz"
  # Honeycomb API key
  HONEYCOMB_API_KEY: "WXlNWGlXMk4yNmlmV2ZGbFJ5eTVXUA=="
