apiVersion: v1
kind: Secret
metadata:
  name: obs-secrets
type: Opaque
data:
  DATABASE_URL: {{ .Values.global.databaseUrl | quote }}
  HONEYCOMB_API_KEY: {{ .Values.global.honeycombApiKey | quote }}
